
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PrimeReactProvider } from "primereact/api";
import { ToastProvider } from "./component/reusable-component/ToastProvider";
import "./globals.css";
import { ClientAuthGuard } from "./lib/ClientAuthGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PrimeReactProvider>
          <ToastProvider>
            <ClientAuthGuard>
              {children}
            </ClientAuthGuard>
          </ToastProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
